---
version: "2.1"
services:
  flaresolverr:
    build: .
    image: tradepending/cloudflare-cookie
    container_name: cloudflare-cookie
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_HTML=${LOG_HTML:-true}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
